//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Player/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""fc69f195-dc85-40f3-ad8d-c569df3806a2"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""2a182664-c483-4292-ac17-729e869249a9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""b17c4aed-ba5d-4cca-874f-9e11ca7e9117"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""5dd1686f-4d17-4d20-9814-91ee476b0cbc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""9752b179-1685-4d91-bef8-89c1d039d91c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Weapon Effect"",
                    ""type"": ""Button"",
                    ""id"": ""9ca6b1e7-5081-46b1-b7fa-54013743d0c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Special Item"",
                    ""type"": ""Button"",
                    ""id"": ""01731cde-8f75-40dc-b1e0-b97db2d47236"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""78bde57f-06c0-4966-8144-174e0a22d667"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""0153511a-5754-4b77-8ac1-fede7a3710ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""One Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""5218f735-2b8e-4f6e-8a49-3aca4f12c9c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""fb43fc55-8b24-435e-ad35-a782aa0fbc5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""31f775a5-e8c0-4e62-8bc4-a918969cd7fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f422f1b4-5854-4f98-a881-c379d23ad384"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2f1899da-f638-4dc4-9158-161f254e18ad"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1003bdd1-7ff4-497c-87e5-80c72260454e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e7dfcda3-30bc-48f4-95f3-c5ff891a8ee9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""99d0060c-04a6-446e-b530-0a7479613044"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""24428238-40e0-48a8-9a1e-ef49de3bb67b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27dca33d-2740-4696-8097-92a9789c23ba"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7dd226c-8987-483c-91b3-7969d4956002"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49accb7f-d870-411f-9f6f-d1f71fc92fee"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Weapon Effect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ada037ec-3d1a-41f4-9a13-377059a07eb1"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Special Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edd1a38f-3145-45a1-8876-c976a3511d41"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b835121a-3e06-4260-93b0-dcf2487d0354"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7732b06-42c7-46fc-bd52-1e4b5ea17ada"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f18ecee-a586-4add-81cd-53ba5a7ea03b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c81a91e7-8638-443b-a7b6-a91503367920"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PassiveSelect"",
            ""id"": ""dca0978e-0171-41af-bc28-8f7454c4fb0f"",
            ""actions"": [
                {
                    ""name"": ""One Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""a0a960ef-e204-42e7-867b-1fb206f533cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""954dd9ba-9473-485c-9d57-b026c53e0524"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""143d4c3f-0af3-4035-ac89-fe2a186b357b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5564bee3-9cb0-40a5-979d-40f052075cad"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9a57e88-b10f-43a8-af1c-09b42f0cb02d"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84c58466-adf2-4ef8-8106-1c41f2601735"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""WeaponReplace"",
            ""id"": ""9f372a46-fe32-4b77-93af-44db526b235a"",
            ""actions"": [
                {
                    ""name"": ""One Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""2128ba78-d0ca-406e-a650-37879fa5ebe4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""dbc1a4d0-9353-4132-9253-c91ca4ac9572"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""6a2f0ad6-fe1a-4f6f-9af3-1094d8a09daf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""31a0bcf1-5999-495b-bcda-b87529ad63d4"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c92e29a0-a527-4a5f-9b83-c704de9881a5"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92fabf29-3b4d-4dfd-b48e-76935bd05a57"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Movement = m_Gameplay.FindAction("Movement", throwIfNotFound: true);
        m_Gameplay_Dash = m_Gameplay.FindAction("Dash", throwIfNotFound: true);
        m_Gameplay_MousePosition = m_Gameplay.FindAction("MousePosition", throwIfNotFound: true);
        m_Gameplay_Interact = m_Gameplay.FindAction("Interact", throwIfNotFound: true);
        m_Gameplay_UseWeaponEffect = m_Gameplay.FindAction("Use Weapon Effect", throwIfNotFound: true);
        m_Gameplay_UseSpecialItem = m_Gameplay.FindAction("Use Special Item", throwIfNotFound: true);
        m_Gameplay_PreviousWeapon = m_Gameplay.FindAction("PreviousWeapon", throwIfNotFound: true);
        m_Gameplay_NextWeapon = m_Gameplay.FindAction("NextWeapon", throwIfNotFound: true);
        m_Gameplay_OneClicked = m_Gameplay.FindAction("One Clicked", throwIfNotFound: true);
        m_Gameplay_TwoClicked = m_Gameplay.FindAction("Two Clicked", throwIfNotFound: true);
        m_Gameplay_ThreeClicked = m_Gameplay.FindAction("Three Clicked", throwIfNotFound: true);
        // PassiveSelect
        m_PassiveSelect = asset.FindActionMap("PassiveSelect", throwIfNotFound: true);
        m_PassiveSelect_OneClicked = m_PassiveSelect.FindAction("One Clicked", throwIfNotFound: true);
        m_PassiveSelect_TwoClicked = m_PassiveSelect.FindAction("Two Clicked", throwIfNotFound: true);
        m_PassiveSelect_ThreeClicked = m_PassiveSelect.FindAction("Three Clicked", throwIfNotFound: true);
        // WeaponReplace
        m_WeaponReplace = asset.FindActionMap("WeaponReplace", throwIfNotFound: true);
        m_WeaponReplace_OneClicked = m_WeaponReplace.FindAction("One Clicked", throwIfNotFound: true);
        m_WeaponReplace_TwoClicked = m_WeaponReplace.FindAction("Two Clicked", throwIfNotFound: true);
        m_WeaponReplace_ThreeClicked = m_WeaponReplace.FindAction("Three Clicked", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_Movement;
    private readonly InputAction m_Gameplay_Dash;
    private readonly InputAction m_Gameplay_MousePosition;
    private readonly InputAction m_Gameplay_Interact;
    private readonly InputAction m_Gameplay_UseWeaponEffect;
    private readonly InputAction m_Gameplay_UseSpecialItem;
    private readonly InputAction m_Gameplay_PreviousWeapon;
    private readonly InputAction m_Gameplay_NextWeapon;
    private readonly InputAction m_Gameplay_OneClicked;
    private readonly InputAction m_Gameplay_TwoClicked;
    private readonly InputAction m_Gameplay_ThreeClicked;
    public struct GameplayActions
    {
        private @PlayerActions m_Wrapper;
        public GameplayActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Gameplay_Movement;
        public InputAction @Dash => m_Wrapper.m_Gameplay_Dash;
        public InputAction @MousePosition => m_Wrapper.m_Gameplay_MousePosition;
        public InputAction @Interact => m_Wrapper.m_Gameplay_Interact;
        public InputAction @UseWeaponEffect => m_Wrapper.m_Gameplay_UseWeaponEffect;
        public InputAction @UseSpecialItem => m_Wrapper.m_Gameplay_UseSpecialItem;
        public InputAction @PreviousWeapon => m_Wrapper.m_Gameplay_PreviousWeapon;
        public InputAction @NextWeapon => m_Wrapper.m_Gameplay_NextWeapon;
        public InputAction @OneClicked => m_Wrapper.m_Gameplay_OneClicked;
        public InputAction @TwoClicked => m_Wrapper.m_Gameplay_TwoClicked;
        public InputAction @ThreeClicked => m_Wrapper.m_Gameplay_ThreeClicked;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                @Dash.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDash;
                @MousePosition.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMousePosition;
                @Interact.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                @UseWeaponEffect.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseWeaponEffect;
                @UseWeaponEffect.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseWeaponEffect;
                @UseWeaponEffect.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseWeaponEffect;
                @UseSpecialItem.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSpecialItem;
                @UseSpecialItem.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSpecialItem;
                @UseSpecialItem.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseSpecialItem;
                @PreviousWeapon.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPreviousWeapon;
                @PreviousWeapon.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPreviousWeapon;
                @PreviousWeapon.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPreviousWeapon;
                @NextWeapon.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnNextWeapon;
                @NextWeapon.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnNextWeapon;
                @NextWeapon.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnNextWeapon;
                @OneClicked.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnOneClicked;
                @OneClicked.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnOneClicked;
                @OneClicked.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnOneClicked;
                @TwoClicked.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnTwoClicked;
                @TwoClicked.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnTwoClicked;
                @TwoClicked.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnTwoClicked;
                @ThreeClicked.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnThreeClicked;
                @ThreeClicked.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnThreeClicked;
                @ThreeClicked.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnThreeClicked;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @UseWeaponEffect.started += instance.OnUseWeaponEffect;
                @UseWeaponEffect.performed += instance.OnUseWeaponEffect;
                @UseWeaponEffect.canceled += instance.OnUseWeaponEffect;
                @UseSpecialItem.started += instance.OnUseSpecialItem;
                @UseSpecialItem.performed += instance.OnUseSpecialItem;
                @UseSpecialItem.canceled += instance.OnUseSpecialItem;
                @PreviousWeapon.started += instance.OnPreviousWeapon;
                @PreviousWeapon.performed += instance.OnPreviousWeapon;
                @PreviousWeapon.canceled += instance.OnPreviousWeapon;
                @NextWeapon.started += instance.OnNextWeapon;
                @NextWeapon.performed += instance.OnNextWeapon;
                @NextWeapon.canceled += instance.OnNextWeapon;
                @OneClicked.started += instance.OnOneClicked;
                @OneClicked.performed += instance.OnOneClicked;
                @OneClicked.canceled += instance.OnOneClicked;
                @TwoClicked.started += instance.OnTwoClicked;
                @TwoClicked.performed += instance.OnTwoClicked;
                @TwoClicked.canceled += instance.OnTwoClicked;
                @ThreeClicked.started += instance.OnThreeClicked;
                @ThreeClicked.performed += instance.OnThreeClicked;
                @ThreeClicked.canceled += instance.OnThreeClicked;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // PassiveSelect
    private readonly InputActionMap m_PassiveSelect;
    private IPassiveSelectActions m_PassiveSelectActionsCallbackInterface;
    private readonly InputAction m_PassiveSelect_OneClicked;
    private readonly InputAction m_PassiveSelect_TwoClicked;
    private readonly InputAction m_PassiveSelect_ThreeClicked;
    public struct PassiveSelectActions
    {
        private @PlayerActions m_Wrapper;
        public PassiveSelectActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @OneClicked => m_Wrapper.m_PassiveSelect_OneClicked;
        public InputAction @TwoClicked => m_Wrapper.m_PassiveSelect_TwoClicked;
        public InputAction @ThreeClicked => m_Wrapper.m_PassiveSelect_ThreeClicked;
        public InputActionMap Get() { return m_Wrapper.m_PassiveSelect; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PassiveSelectActions set) { return set.Get(); }
        public void SetCallbacks(IPassiveSelectActions instance)
        {
            if (m_Wrapper.m_PassiveSelectActionsCallbackInterface != null)
            {
                @OneClicked.started -= m_Wrapper.m_PassiveSelectActionsCallbackInterface.OnOneClicked;
                @OneClicked.performed -= m_Wrapper.m_PassiveSelectActionsCallbackInterface.OnOneClicked;
                @OneClicked.canceled -= m_Wrapper.m_PassiveSelectActionsCallbackInterface.OnOneClicked;
                @TwoClicked.started -= m_Wrapper.m_PassiveSelectActionsCallbackInterface.OnTwoClicked;
                @TwoClicked.performed -= m_Wrapper.m_PassiveSelectActionsCallbackInterface.OnTwoClicked;
                @TwoClicked.canceled -= m_Wrapper.m_PassiveSelectActionsCallbackInterface.OnTwoClicked;
                @ThreeClicked.started -= m_Wrapper.m_PassiveSelectActionsCallbackInterface.OnThreeClicked;
                @ThreeClicked.performed -= m_Wrapper.m_PassiveSelectActionsCallbackInterface.OnThreeClicked;
                @ThreeClicked.canceled -= m_Wrapper.m_PassiveSelectActionsCallbackInterface.OnThreeClicked;
            }
            m_Wrapper.m_PassiveSelectActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OneClicked.started += instance.OnOneClicked;
                @OneClicked.performed += instance.OnOneClicked;
                @OneClicked.canceled += instance.OnOneClicked;
                @TwoClicked.started += instance.OnTwoClicked;
                @TwoClicked.performed += instance.OnTwoClicked;
                @TwoClicked.canceled += instance.OnTwoClicked;
                @ThreeClicked.started += instance.OnThreeClicked;
                @ThreeClicked.performed += instance.OnThreeClicked;
                @ThreeClicked.canceled += instance.OnThreeClicked;
            }
        }
    }
    public PassiveSelectActions @PassiveSelect => new PassiveSelectActions(this);

    // WeaponReplace
    private readonly InputActionMap m_WeaponReplace;
    private IWeaponReplaceActions m_WeaponReplaceActionsCallbackInterface;
    private readonly InputAction m_WeaponReplace_OneClicked;
    private readonly InputAction m_WeaponReplace_TwoClicked;
    private readonly InputAction m_WeaponReplace_ThreeClicked;
    public struct WeaponReplaceActions
    {
        private @PlayerActions m_Wrapper;
        public WeaponReplaceActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @OneClicked => m_Wrapper.m_WeaponReplace_OneClicked;
        public InputAction @TwoClicked => m_Wrapper.m_WeaponReplace_TwoClicked;
        public InputAction @ThreeClicked => m_Wrapper.m_WeaponReplace_ThreeClicked;
        public InputActionMap Get() { return m_Wrapper.m_WeaponReplace; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WeaponReplaceActions set) { return set.Get(); }
        public void SetCallbacks(IWeaponReplaceActions instance)
        {
            if (m_Wrapper.m_WeaponReplaceActionsCallbackInterface != null)
            {
                @OneClicked.started -= m_Wrapper.m_WeaponReplaceActionsCallbackInterface.OnOneClicked;
                @OneClicked.performed -= m_Wrapper.m_WeaponReplaceActionsCallbackInterface.OnOneClicked;
                @OneClicked.canceled -= m_Wrapper.m_WeaponReplaceActionsCallbackInterface.OnOneClicked;
                @TwoClicked.started -= m_Wrapper.m_WeaponReplaceActionsCallbackInterface.OnTwoClicked;
                @TwoClicked.performed -= m_Wrapper.m_WeaponReplaceActionsCallbackInterface.OnTwoClicked;
                @TwoClicked.canceled -= m_Wrapper.m_WeaponReplaceActionsCallbackInterface.OnTwoClicked;
                @ThreeClicked.started -= m_Wrapper.m_WeaponReplaceActionsCallbackInterface.OnThreeClicked;
                @ThreeClicked.performed -= m_Wrapper.m_WeaponReplaceActionsCallbackInterface.OnThreeClicked;
                @ThreeClicked.canceled -= m_Wrapper.m_WeaponReplaceActionsCallbackInterface.OnThreeClicked;
            }
            m_Wrapper.m_WeaponReplaceActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OneClicked.started += instance.OnOneClicked;
                @OneClicked.performed += instance.OnOneClicked;
                @OneClicked.canceled += instance.OnOneClicked;
                @TwoClicked.started += instance.OnTwoClicked;
                @TwoClicked.performed += instance.OnTwoClicked;
                @TwoClicked.canceled += instance.OnTwoClicked;
                @ThreeClicked.started += instance.OnThreeClicked;
                @ThreeClicked.performed += instance.OnThreeClicked;
                @ThreeClicked.canceled += instance.OnThreeClicked;
            }
        }
    }
    public WeaponReplaceActions @WeaponReplace => new WeaponReplaceActions(this);
    public interface IGameplayActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnUseWeaponEffect(InputAction.CallbackContext context);
        void OnUseSpecialItem(InputAction.CallbackContext context);
        void OnPreviousWeapon(InputAction.CallbackContext context);
        void OnNextWeapon(InputAction.CallbackContext context);
        void OnOneClicked(InputAction.CallbackContext context);
        void OnTwoClicked(InputAction.CallbackContext context);
        void OnThreeClicked(InputAction.CallbackContext context);
    }
    public interface IPassiveSelectActions
    {
        void OnOneClicked(InputAction.CallbackContext context);
        void OnTwoClicked(InputAction.CallbackContext context);
        void OnThreeClicked(InputAction.CallbackContext context);
    }
    public interface IWeaponReplaceActions
    {
        void OnOneClicked(InputAction.CallbackContext context);
        void OnTwoClicked(InputAction.CallbackContext context);
        void OnThreeClicked(InputAction.CallbackContext context);
    }
}
